kind: pipeline
type: docker
name: default

steps:
- name: testing
  image: golang:1.21
  commands:
  - go test -v .

- name: publish
  pull: always
  image: thegeeklab/drone-docker-buildx:23
  privileged: true
  environment:
    DRONE_REPO_BRANCH: main
  settings:
    Dockerfile: Dockerfile
    auto_tag: true
    password:
      from_secret: docker_password
    repo: appleboy/hello-drone-cht
    username:
      from_secret: docker_username
    platforms:
      - linux/amd64
      - linux/arm64
